export const MyActions = {

    "ADDTOMYLIST":"ADDTOMYLIST",
    "REMOVEFROMLIST" :"REMOVEFROMLIST",
    "GETALLLIST":"GETALLLIST",
    "SETCURRENTSEASON":"SETCURRENTSEASON",
    "SETCURRENTEPISODE":"SETCURRENTEPISODE",
    "GETCURRENTSTATES":"GETCURRENTSTATES",
    "SETCONTINUEWATCHING":"SETCONTINUEWATCHING",
    "GETCONTINUEWATCHING":"GETCONTINUEWATCHING"

}